<a href="https://colab.research.google.com/github/Johanson20/HDSC_StageC/blob/master/quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import Relevant Libraries

In [1]:
import numpy as np
import pandas as pd

df1 = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')

In [2]:
df1.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stab', 'stabf'],
      dtype='object')

In [3]:
df = df1.drop('stab', axis=1)
df.describe()

tau1          tau2  ...            g3            g4
count  10000.000000  10000.000000  ...  10000.000000  10000.000000
mean       5.250000      5.250001  ...      0.525000      0.525000
std        2.742548      2.742549  ...      0.274255      0.274255
min        0.500793      0.500141  ...      0.050054      0.050028
25%        2.874892      2.875140  ...      0.287514      0.287494
50%        5.250004      5.249981  ...      0.525015      0.525002
75%        7.624690      7.624893  ...      0.762440      0.762433
max        9.999469      9.999837  ...      0.999982      0.999930

[8 rows x 12 columns]

In [4]:
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

In [5]:
df.head()

tau1      tau2      tau3  ...        g3        g4     stabf
0  2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1  9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2  8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3  0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4  3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable

[5 rows x 13 columns]

In [6]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [64]:
X = df.drop('stabf', axis=1)
y = df['stabf']

In [88]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [104]:
y_train.value_counts()

unstable    5092
stable      2908
Name: stabf, dtype: int64

##Scale X-values

In [105]:
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
normalised_train_df = scaler.fit_transform(x_train)
normalised_train_df = pd.DataFrame(normalised_train_df, columns=x_train.columns)
normalised_train_df.head()

tau1      tau2      tau3  ...        g2        g3        g4
0  0.605895  0.214898  0.686826  ...  0.598331  0.669360  0.642234
1  0.481097  0.525305  0.797470  ...  0.049680  0.912824  0.083403
2  0.075724  0.874245  0.355155  ...  0.919622  0.198830  0.642306
3  0.736693  0.652439  0.873580  ...  0.893734  0.963154  0.579607
4  0.692014  0.088023  0.589553  ...  0.701163  0.828559  0.121206

[5 rows x 12 columns]

In [106]:
normalised_test_df = scaler.transform(x_test)
normalised_test_df = pd.DataFrame(normalised_test_df, columns=x_test.columns)
normalised_test_df.head()

tau1      tau2      tau3  ...        g2        g3        g4
0  0.671365  0.380367  0.932340  ...  0.837447  0.065691  0.813278
1  0.558188  0.607557  0.445405  ...  0.385755  0.908498  0.854065
2  0.188048  0.408938  0.245239  ...  0.084360  0.688470  0.014509
3  0.475764  0.179892  0.606958  ...  0.016780  0.397283  0.804946
4  0.752247  0.914666  0.524646  ...  0.075332  0.776320  0.263485

[5 rows x 12 columns]

In [107]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(normalised_train_df, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [108]:
from sklearn.metrics import accuracy_score, confusion_matrix
new_predictions = log_reg.predict(normalised_test_df)

In [109]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(log_reg, normalised_train_df, y_train, cv= 5 , scoring= 'f1_macro' )
scores

array([0.8049015 , 0.80345987, 0.80692585, 0.79706083, 0.78410765])

In [116]:
cnf_mat = confusion_matrix(y_true=y_test, y_pred=new_predictions, labels=['stable' , 'unstable'])
cnf_mat

array([[ 493,  219],
       [ 173, 1115]])

##Random Forest Classifier

In [125]:
from sklearn.ensemble import RandomForestClassifier
rfs = RandomForestClassifier(random_state=1)

In [126]:
rfs.fit(normalised_train_df, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [127]:
new_pred = rfs.predict(normalised_test_df)
accuracy = accuracy_score(y_true=y_test, y_pred=new_pred)
print( 'Accuracy: {}' .format(round(accuracy* 100 ), 5))

Accuracy: 93.0


## XGBoost Classifier

In [128]:
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state=1)
xgb.fit(normalised_train_df, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [130]:
new_pred1 = xgb.predict(normalised_test_df)
accuracy = accuracy_score(y_true=y_test, y_pred=new_pred1)
print( 'Accuracy: {}' .format(round(accuracy* 100 ), 5))

Accuracy: 92.0


## LightGBM Classifier

In [131]:
import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(normalised_train_df, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [133]:
new_pred2 = clf.predict(normalised_test_df)
accuracy = accuracy_score(y_true=y_test, y_pred=new_pred2)
print( 'Accuracy: {}' .format(round(accuracy* 100 ), 5))

Accuracy: 94.0


##Extra Trees Classifier with Hyperparameters

In [134]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2,3,5,7,9]
min_samples_leaf = [1,2,4,6,8,9]
max_features=['auto', 'sqrt', 'log2', 'None']
hyperparameter_grid = {'n_estimators': n_estimators,

                       'min_samples_leaf': min_samples_leaf,

                       'min_samples_split': min_samples_split,

                       'max_features': max_features}

In [135]:
xtree = ExtraTreesClassifier()
rndsmodel = RandomizedSearchCV(xtree, hyperparameter_grid, random_state=1)

In [137]:
rndsmodel.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Invalid value for max_features. Allowed string values are 'auto', 'sqrt' or 'log2'.

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Invalid value for max_features. Allowed string values are 'auto', 'sqrt' or 'log2'.

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Invalid value for max_features. Allowed string values are 'auto', 'sqrt' or 'log2'.

  FitFailedWarning)
/usr/local

RandomizedSearchCV(cv=None, error_score=nan,
                   estimator=ExtraTreesClassifier(bootstrap=False,
                                                  ccp_alpha=0.0,
                                                  class_weight=None,
                                                  criterion='gini',
                                                  max_depth=None,
                                                  max_features='auto',
                                                  max_leaf_nodes=None,
                                                  max_samples=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                     

In [138]:
xtree_pred=rndsmodel.predict(x_test)
xtree_pred

array(['unstable', 'unstable', 'stable', ..., 'stable', 'unstable',
       'unstable'], dtype=object)

In [141]:
xtree.fit(normalised_train_df, y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

##Feature Importance

In [142]:
xtree.feature_importances_

array([0.11856766, 0.1182068 , 0.1130969 , 0.11444941, 0.03904175,
       0.04076367, 0.04040279, 0.03984601, 0.09012502, 0.09556876,
       0.09686568, 0.09306555])

In [143]:
x_train.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4'],
      dtype='object')